name = "lidar_kf"
uuid = "251db725-f011-4fdc-93f2-655439c157b6"
authors = ["Vladyslav Kinzerskiy <vladyslav.kinzerskiy@porsche-engineering.ro>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
